Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads  # 上传文件的最终保存目录
  UploadServerUrl: http://127.0.0.1:8080/static #上传文件后的用于展示的文件服务地址
  UploadImageMaxSize: 5  # 上传文件所允许的最大空间大小（MB）
  UploadImageAllowExts:  # 上传文件所允许的文件后缀
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 60
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: lewis
  Issuer: blog-service
  Expire: 7200